### ISSUE TITLE
Limits should limit total count of function calls rather than algo iterations

### ISSUE THREAD

**Issue by KOLANICH** [ecrl/ecabc#14]
Since the iterations involving no evaluations are cheap, but iterations involving evaluations are expensive and I cannot predict count of evaluations per iteration. For example I allocate the budget of 1000 evaluations, but de-facto the function is evaluated only ~300 times.

**Comment by hgromer** [comment]
This may be due to the fact that bees with cost >= the average cost of all bees keep their values for the iteration. This is by design. An iteration is when you iterate through all the bees to get rid of poorly performing ones, and replace their values/cost. This ensures that you are pursuing an optimal path. It doesn't make sense to replace well performing bees. My partner is currently revamping the algorithm to adjust to some research she has done. If you want to increase the amount of times you are performing the fitness function, I would increase the population of your employer bees.

**Comment by KOLANICH** [comment]
>This may be due to the fact that bees with cost >= the average cost of all bees keep their values for the iteration. This is by design. 

I know.

>If you want to increase the amount of times you are performing the fitness function, I would increase the population of your employer bees.

It still doesn't give predictable number of evaluations. I mean IMHO it makes no sense to limit number of algo iterations (I call them generations because the algo seems to be a genetic algo) because resource consumption is determined by evaluations, and in much less grade (initialization and memory), by the size of population, so we should limit number of actual evaluations instead.

**Comment by hgromer** [comment]
I will talk with the rest of my team to see what they think about this. I'm not sure termination based on resources is a broad enough use case where it will be worth implementing a change in order to do so. The way we have been using it, and have seen most people use it, is per iteration the way it is now, or per target value (the most common). I'm not sure it would make sense to terminate halfway through a 'generation' due to resource constraints, but we'll look into it.

It wouldn't be a hard change, it can actually be very easily implemented, but may not be worth it, and may be more confusing to users going forward.

***UPDATE***
Decided that this use case wasn't broad enough. Avoiding change to prevent confusion. Calculating of function class calls can be done per iteration of the supplied function, and set the number of iterations accordingly.

**Comment by KOLANICH** [comment]
OK.
