### ISSUE TITLE
Update fitness score method breaks the code and doesn't update the bee correctly

### ISSUE THREAD

**Issue by hgromer** [ecrl/ecabc#36]
What is this doing here? You removed the check for None (this will break). You're also never updating the values, and you're changing the fitness score of the bee.

The fitness of a bee should just be the fitness score returned from the user defined fitness function. And you need to properly associate the correct set of values with that score.

_Originally posted by @hgromer in https://github.com/ECRL/ecabc/commit/4e4fcb7cae5910c3f9fdabb8775a9a20398430c0#commitcomment-31710899_

**Comment by sanskriti-s** [comment]
Taking out the check was my bad. But the fitness score isn't simply the return value. It has to be passed through that math. https://abc.erciyes.edu.tr/pub/Step%20by%20Step%20Procedure%20of%20ABC.pdf

**Comment by hgromer** [comment]
I think that may be their actual fitness function? Wikipedia doesn't mention this. I don't see how it would be beneficial, I feel like it would obfuscate the results from the user. IE, a user won't understand what a good 'target' fitness score is because his fitness score is being modified in a weird way. 

Again, I think this may be their 'literal' fitness function, not the general case for all fitness functions. I don't see it mentioned on wikipedia https://en.wikipedia.org/wiki/Artificial_bee_colony_algorithm

**Comment by sanskriti-s** [comment]
The wikipedia article isn't complete. I have seen this is multiple papers. I'll be honest I"m not entirely sure of the purpose it serves but it's definitely a part of the algorithm

**Comment by hgromer** [comment]
Interesting, maybe we should run some tests to see if it performs better. If it doesn't, I think implementing it may be confusing. And lets make sure the values associated to the fitness score are also updated here.

**Comment by sanskriti-s** [comment]
I think it's a good idea to test it. But I don't see how we can use someone algorithm and then change it when we feel like

**Comment by tjkessler** [comment]
From what I can tell, the purpose of these functions is to standardize/normalize fitness (between 0 and 1 if positive, 1 + abs(fitness) if negative). The math forces the fitness towards 0, regardless of it being positive or negative.

**Comment by sanskriti-s** [comment]
That makes sense

**Comment by hgromer** [comment]
I still think it can be confusing. If the user has a target fitness value they want to achieve, they can no longer iterate to that point. Just a thought though.

**Comment by sanskriti-s** [comment]
Since the output we are getting is the error, we want the fitness score to be lower the higher the error is. If we assign the error to the fitness directly, a higher error will equal a higher fitness (which messes up the algorithm).

The formula 1/(1+f(x)) inverts it so a higher error equates to a lower fitness score.

**Comment by sanskriti-s** [comment]
Additionally, there are some problems I found with the get_fitness_score function in the first place
1. It is never called anywhere (abc.py always calls fitness function directly)
2. Simply getting and setting the fitness function should not check whether to keep a score/set of values because it has not looked at probability yet. (This is also why the function should not do a null check, since it should not be looking at its own score at all, only assigning to it. The logic for keeping vs discarding a position shouldn't be in this function)
3. The function is assuming the values passed into get_fitness_function have not been saved yet, which requires that “generate random values” be passed directly to the function (as opposed to setting bee.values equal to random numbers, then passing bee.values to get_fitness_function)
4. The function is named with “get” yet doesn’t return anything. If this is intentional it should be changed to something like “calculate”

**Comment by hgromer** [comment]
I think all that sounds good, just keep in mind that at the end of the day, the user must be able to terminate the program based on an end result value that makes intuitive sense to them.
