### ISSUE TITLE
Fix multiprocessing

### ISSUE THREAD

**Issue by sanskriti-s** [ecrl/ecabc#37]
https://github.com/ECRL/ecabc/blob/2.2.0/ecabc/abc.py#L223

**Comment by sanskriti-s** [comment]
The get_fitness_score needs to be there but putting it directly after the multiprocessing would ruin the point of putting through multiprocessing so we need to think of a better way to implement this

**Comment by hgromer** [comment]
Yeah, the code was right before. It doesn’t work the way it’s written now. You can’t call get fitness score on a future, which is what you’re doing now. Not sure why this was changed. If you try running this code I’m 99.9% sure it’ll break.

**Comment by sanskriti-s** [comment]
It definitely won't work now, it was just a placeholder. I only put it there because the function needs to be called. Like I said originally, we need to find a way to actually implement this. Any ideas?
One thing I'm thinking of is making the get_fitness_score call the fitness function and then async calling the get_fitness_score

**Comment by hgromer** [comment]
I'm confused as what the actual issue is. It worked before, but if you are modifying the get fitness score method you have to accommodate this accordingly. I'm not sure how you are planning to change it. Essentially you want the fitness score function to be called on operate process and you want to then make sure all processes finish and all scores have been calculated before you move to the next method call.
