### ISSUE TITLE
You shouldn't mess with global objects like `sys.stdout`

### ISSUE THREAD

**Issue by KOLANICH** [ecrl/ecabc#5]
Because it interferes with the rest of program.

Instead you should define a property in a class and set it to `print` by default and use only it.

**Comment by hgromer** [comment]
What do you mean interferes with the program? Sys.stdout is reset to default when the program terminates.  I can look into this for 1.2, but if there is a specific bug or issue you are running into please let me know. I can see potential errors when throwing exceptions/concurrent programming.

**Comment by KOLANICH** [comment]
>Sys.stdout is reset to default when the program terminates. 

I use `tqdm` for progress and output, progress reporting is built into my function (because it is generic enough, I created the architecture where it is easy to plug an optimizer and plugged more than 10 different optimizers) I wanna optimize.

tqdm requires all the code within it to output via its method. Otherwise CLI is disrupted. Also I did some experiments (I have no code of them now) and sometimes have seen no output where it should be.

**Comment by hgromer** [comment]
Sure, I agree this is an issue that needs addressing, we have a large patch coming out. Both I and the other developer are busy with school/work right now, but I'm planning on releasing by next Monday. This patch will change this lazy implementation of modifying sys.stdout.

This has now been fixed in 1.2.0. This will shortly be up on Pypi, however feel free to download the 1.2.0 branch and run setup.py yourself.
