### ISSUE TITLE
White in the docs what is controlled by each hyperparam

### ISSUE THREAD

**Issue by KOLANICH** [ecrl/ecabc#8]

**Comment by hgromer** [comment]
I don’t understand this issue.

**Comment by KOLANICH** [comment]
I wonder how `iterationAmount` and  `amountOfEmployer` affect count of calls and expected distance to global optimum.

**Comment by hgromer** [comment]
iterationAmount: The amount of iterations you would like the program to undergo before terminating
amountOfEmployer: The amount of employer bees the artificial colony will contain, each containing its own set of value and fitness scores correlating to the values.

An iteration is defined as a set of X employers calculating the fitness score for X different locations/values, then creating new sets of values based on an algorithm to assign to employers. amountOfEmployers specifies the amount of locations-values pair values per iteration. 

Having more employers theoretically means you are trying a greater variety of values, and thus will reach your target fitness score in less iterations, however, each iteration will take longer because you are processing more values.
